# Generated by tools/tdgen.py. Do not edit directly.
execute if items entity @s weapon.mainhand minecraft:carrot_on_a_stick[custom_data~{td:{tool:"tower",tower:"blink"}}] run function td:tower/select/blink
