# Generated by tools/tdgen.py. Do not edit directly.
# 현재 위치에 fast 타입 적을 소환하고 초기화합니다.
summon minecraft:vindicator ~ ~ ~ {Tags:["td.enemy","td.new","td.type.fast"],NoAI:1b,NoGravity:1b,PersistenceRequired:1b,Silent:1b,CustomName:{text:'Fast',color:'yellow'},CustomNameVisible:1b}

execute as @e[tag=td.new,tag=td.type.fast,sort=nearest,limit=1] at @s run function td:enemy/type/fast
execute as @e[tag=td.new,tag=td.type.fast,sort=nearest,limit=1] at @s run function td:spawn/common
