# Generated by tools/tdgen.py. Do not edit directly.
# boss 적 설정입니다.
scoreboard players set $enemy_boss_hp td.enemy_max_hp 100
scoreboard players set $enemy_boss_speed td.speed 1
scoreboard players set $enemy_boss_reward td.reward 80
scoreboard players set $enemy_boss_core_damage td.core_damage 10
