# Generated by tools/tdgen.js. Do not edit directly.
# tank 적 설정입니다.
scoreboard players set $enemy_tank_hp td.enemy_max_hp 30
scoreboard players set $enemy_tank_speed td.speed 1
scoreboard players set $enemy_tank_reward td.reward 15
scoreboard players set $enemy_tank_core_damage td.core_damage 3
