# Generated by tools/tdgen.js. Do not edit directly.
# boss 타입 설정입니다.
# HP, speed, reward, core damage는 td:config/enemy/boss에서 가져옵니다.
tag @s add td.type.boss
scoreboard players operation @s td.enemy_max_hp = $enemy_boss_hp td.enemy_max_hp
scoreboard players operation @s td.enemy_hp = $enemy_boss_hp td.enemy_max_hp
scoreboard players operation @s td.speed = $enemy_boss_speed td.speed
scoreboard players operation @s td.reward = $enemy_boss_reward td.reward
scoreboard players operation @s td.core_damage = $enemy_boss_core_damage td.core_damage

# 팀 색상과 충돌 방지 규칙을 적용합니다.
team join td_enemy_boss @s

attribute @s minecraft:scale base set 1.5

item replace entity @s armor.head with minecraft:golden_helmet
item replace entity @s weapon.mainhand with minecraft:blaze_rod

particle minecraft:enchant ~ ~1.2 ~ 0.6 0.7 0.6 0.2 40
playsound minecraft:entity.evoker.ambient master @a[distance=..24] ~ ~ ~ 0.8 0.7
