# Generated by tools/tdgen.js. Do not edit directly.
# fast 타입 설정입니다.
# HP, speed, reward, core damage는 td:config/enemy/fast에서 가져옵니다.
tag @s add td.type.fast
scoreboard players operation @s td.enemy_max_hp = $enemy_fast_hp td.enemy_max_hp
scoreboard players operation @s td.enemy_hp = $enemy_fast_hp td.enemy_max_hp
scoreboard players operation @s td.speed = $enemy_fast_speed td.speed
scoreboard players operation @s td.reward = $enemy_fast_reward td.reward
scoreboard players operation @s td.core_damage = $enemy_fast_core_damage td.core_damage

# 팀 색상과 충돌 방지 규칙을 적용합니다.
team join td_enemy_fast @s

attribute @s minecraft:scale base set 0.85

item replace entity @s weapon.mainhand with minecraft:iron_axe

particle minecraft:crit ~ ~1 ~ 0.35 0.35 0.35 0.1 12
playsound minecraft:entity.vindicator.ambient master @a[distance=..16] ~ ~ ~ 0.45 1.5
