# Generated by tools/tdgen.js. Do not edit directly.
# tank 타입 설정입니다.
# HP, speed, reward, core damage는 td:config/enemy/tank에서 가져옵니다.
tag @s add td.type.tank
scoreboard players operation @s td.enemy_max_hp = $enemy_tank_hp td.enemy_max_hp
scoreboard players operation @s td.enemy_hp = $enemy_tank_hp td.enemy_max_hp
scoreboard players operation @s td.speed = $enemy_tank_speed td.speed
scoreboard players operation @s td.reward = $enemy_tank_reward td.reward
scoreboard players operation @s td.core_damage = $enemy_tank_core_damage td.core_damage

# 팀 색상과 충돌 방지 규칙을 적용합니다.
team join td_enemy_tank @s

attribute @s minecraft:scale base set 1.25

item replace entity @s armor.head with minecraft:iron_helmet
item replace entity @s weapon.offhand with minecraft:shield

particle minecraft:poof ~ ~1 ~ 0.5 0.45 0.5 0.02 18
playsound minecraft:entity.pillager.ambient master @a[distance=..16] ~ ~ ~ 0.5 0.8
