# Generated by tools/tdgen.js. Do not edit directly.
# 적 타입별 팀을 만들고 색상과 충돌 규칙을 설정합니다.
team add td_enemy_basic
team modify td_enemy_basic color green
team modify td_enemy_basic collisionRule never

team add td_enemy_fast
team modify td_enemy_fast color yellow
team modify td_enemy_fast collisionRule never

team add td_enemy_tank
team modify td_enemy_tank color aqua
team modify td_enemy_tank collisionRule never

team add td_enemy_boss
team modify td_enemy_boss color dark_purple
team modify td_enemy_boss collisionRule never

# 방어 유닛은 적 경로와 플레이어 이동을 방해하지 않도록 충돌을 끕니다.
team add td_tower
team modify td_tower color blue
team modify td_tower collisionRule never
