# Generated by tools/tdgen.py. Do not edit directly.
execute if entity @s[tag=td.type.boss] run tag @s add td.hpbar.matched
execute if entity @s[tag=td.type.boss] run function td:enemy/hpbar/type/boss
