# Generated by tools/tdgen.js. Do not edit directly.
execute if entity @s[tag=td.type.fast] run tag @s add td.hpbar.matched
execute if entity @s[tag=td.type.fast] run function td:enemy/hpbar/type/fast
