# Generated by tools/tdgen.js. Do not edit directly.
execute if entity @s[tag=td.type.tank] run tag @s add td.hpbar.matched
execute if entity @s[tag=td.type.tank] run function td:enemy/hpbar/type/tank
