# Generated by tools/tdgen.py. Do not edit directly.
# 코어와 웨이브 진행 기본값입니다.
scoreboard players set $core_hp td.hp 20
scoreboard players set $wave_prep_ticks td.wave_prep 600
scoreboard players set $hp_scale td.tmp 10
scoreboard players set $last_wave td.wave 20
