# Generated by tools/tdgen.js. Do not edit directly.
execute as @e[type=minecraft:mannequin,tag=td.tower.basic,tag=!td.tower.blinking,scores={td.tower_cd=40..}] at @s if entity @e[tag=td.enemy,distance=..8,limit=1,sort=nearest] run function td:tower/attack/run/basic
