# Generated by tools/tdgen.py. Do not edit directly.
# Wave 11: fast x18 + basic x8.
execute if score $wave_time td.wave_time matches 20 run function td:spawn/random {type:"fast"}
execute if score $wave_time td.wave_time matches 40 run function td:spawn/random {type:"fast"}
execute if score $wave_time td.wave_time matches 60 run function td:spawn/random {type:"fast"}
execute if score $wave_time td.wave_time matches 70 run function td:spawn/random {type:"basic"}
execute if score $wave_time td.wave_time matches 80 run function td:spawn/random {type:"fast"}
execute if score $wave_time td.wave_time matches 100 run function td:spawn/random {type:"fast"}
execute if score $wave_time td.wave_time matches 120 run function td:spawn/random {type:"fast"}
execute if score $wave_time td.wave_time matches 130 run function td:spawn/random {type:"basic"}
execute if score $wave_time td.wave_time matches 140 run function td:spawn/random {type:"fast"}
execute if score $wave_time td.wave_time matches 160 run function td:spawn/random {type:"fast"}
execute if score $wave_time td.wave_time matches 180 run function td:spawn/random {type:"fast"}
execute if score $wave_time td.wave_time matches 190 run function td:spawn/random {type:"basic"}
execute if score $wave_time td.wave_time matches 200 run function td:spawn/random {type:"fast"}
execute if score $wave_time td.wave_time matches 220 run function td:spawn/random {type:"fast"}
execute if score $wave_time td.wave_time matches 240 run function td:spawn/random {type:"fast"}
execute if score $wave_time td.wave_time matches 250 run function td:spawn/random {type:"basic"}
execute if score $wave_time td.wave_time matches 260 run function td:spawn/random {type:"fast"}
execute if score $wave_time td.wave_time matches 280 run function td:spawn/random {type:"fast"}
execute if score $wave_time td.wave_time matches 300 run function td:spawn/random {type:"fast"}
execute if score $wave_time td.wave_time matches 310 run function td:spawn/random {type:"basic"}
execute if score $wave_time td.wave_time matches 320 run function td:spawn/random {type:"fast"}
execute if score $wave_time td.wave_time matches 340 run function td:spawn/random {type:"fast"}
execute if score $wave_time td.wave_time matches 360 run function td:spawn/random {type:"fast"}
execute if score $wave_time td.wave_time matches 370 run function td:spawn/random {type:"basic"}
execute if score $wave_time td.wave_time matches 410 run function td:spawn/random {type:"basic"}
execute if score $wave_time td.wave_time matches 450 run function td:spawn/random {type:"basic"}
execute if score $wave_time td.wave_time matches 480 run scoreboard players set $wave_done td.wave_done 1
