# Generated by tools/tdgen.js. Do not edit directly.
# basic 방어 유닛 설정입니다.
# 사거리 8, 공격 주기 40틱입니다.
tag @s add td.tower.basic
scoreboard players operation @s td.tower_cd = $tower_basic_initial_cd td.tower_cd
function td:tower/assign_id

team join td_tower @s
attribute @s minecraft:scale base set 1.0

item replace entity @s weapon.mainhand with minecraft:iron_sword
item replace entity @s armor.head with minecraft:leather_helmet

particle minecraft:happy_villager ~ ~1 ~ 0.3 0.4 0.3 0 8
playsound minecraft:block.note_block.pling master @a[distance=..16] ~ ~ ~ 0.6 1.4

tag @s remove td.tower.new
