#!/usr/bin/env node
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const THIS_FILE = fileURLToPath(import.meta.url);
const ROOT = path.resolve(path.dirname(THIS_FILE), "..");
const DATA = path.join(ROOT, "data", "td");
const FUNCTION = path.join(DATA, "function");
const TAG = path.join(DATA, "tags", "function");
const SPEC = path.join(ROOT, "tools", "spec");
const ARCHIVE = path.join(SPEC, "archive");

const GENERATED = "# Generated by tools/tdgen.js. Do not edit directly.";
const LEGACY_GENERATED = "# Generated by tools/tdgen.py. Do not edit directly.";
const TYPE_RE = /^[a-z0-9_]+$/;
const HP_COLORS = {
  10: "green",
  9: "green",
  8: "green",
  7: "yellow",
  6: "yellow",
  5: "yellow",
  4: "gold",
  3: "gold",
  2: "red",
  1: "dark_red",
};

class TdgenError extends Error {
  constructor(message) {
    super(message);
    this.name = "TdgenError";
  }
}

function rel(filePath) {
  return path.relative(ROOT, filePath).split(path.sep).join("/");
}

function readJson(filePath) {
  try {
    return JSON.parse(fs.readFileSync(filePath, "utf8"));
  } catch (error) {
    if (error.code === "ENOENT") {
      throw new TdgenError(`Missing spec file: ${rel(filePath)}`);
    }
    if (error instanceof SyntaxError) {
      throw new TdgenError(`Invalid JSON in ${rel(filePath)}: ${error.message}`);
    }
    throw error;
  }
}

function writeJson(filePath, value) {
  fs.mkdirSync(path.dirname(filePath), { recursive: true });
  fs.writeFileSync(filePath, `${JSON.stringify(value, null, 2)}\n`, "utf8");
}

function writeFunction(relPath, lines) {
  const filePath = path.join(FUNCTION, `${relPath}.mcfunction`);
  fs.mkdirSync(path.dirname(filePath), { recursive: true });
  const content = [GENERATED, ...lines].join("\n").replace(/\s+$/u, "");
  fs.writeFileSync(filePath, `${content}\n`, "utf8");
}

function writeTag(relPath, values) {
  writeJson(path.join(TAG, `${relPath}.json`), { values });
}

function ns(functionPath) {
  return `td:${functionPath}`;
}

function listJsonFiles(directory) {
  if (!fs.existsSync(directory)) {
    return [];
  }
  return fs
    .readdirSync(directory, { withFileTypes: true })
    .filter((entry) => entry.isFile() && entry.name.endsWith(".json"))
    .map((entry) => path.join(directory, entry.name))
    .sort();
}

function specSortValue(spec) {
  return spec.id ?? spec.number ?? 0;
}

function compareSpecs(left, right) {
  const leftOrder = left.order ?? 1000;
  const rightOrder = right.order ?? 1000;
  if (leftOrder !== rightOrder) {
    return leftOrder < rightOrder ? -1 : 1;
  }
  const leftValue = specSortValue(left);
  const rightValue = specSortValue(right);
  if (typeof leftValue === "number" && typeof rightValue === "number") {
    return leftValue - rightValue;
  }
  return String(leftValue).localeCompare(String(rightValue));
}

function loadSpecs(kind) {
  const specs = [];
  for (const filePath of listJsonFiles(path.join(SPEC, kind))) {
    const value = readJson(filePath);
    if (value.enabled ?? true) {
      value._path = rel(filePath);
      specs.push(value);
    }
  }
  return specs.sort(compareSpecs);
}

function loadGame() {
  const game = readJson(path.join(SPEC, "game.json"));
  return {
    core_hp: game.core_hp ?? 20,
    wave_prep_ticks: game.wave_prep_ticks ?? 600,
    hp_scale: game.hp_scale ?? 10,
    start_money: game.start_money ?? 60,
    combat_refund_divisor: game.combat_refund_divisor ?? 2,
    tower_team: game.tower_team ?? {
      name: "td_tower",
      color: "blue",
      collision_rule: "never",
    },
  };
}

function compactJson(value) {
  return JSON.stringify(value);
}

function snbtString(value) {
  return `'${String(value).replaceAll("\\", "\\\\").replaceAll("'", "\\'")}'`;
}

function scoreboardName(prefix, typeId, suffix) {
  return `$${prefix}_${typeId}_${suffix}`;
}

function formatScale(value) {
  const scale = value ?? 1.0;
  return Number.isInteger(scale) ? `${scale}.0` : String(scale);
}

function generatedFile(filePath) {
  if (!fs.existsSync(filePath) || !fs.statSync(filePath).isFile()) {
    return false;
  }
  const firstLine = fs.readFileSync(filePath, "utf8").split(/\r?\n/u, 1)[0] ?? "";
  return firstLine === GENERATED || firstLine === LEGACY_GENERATED;
}

function cleanGeneratedFiles() {
  const ownedDirs = [
    path.join(FUNCTION, "config", "enemy"),
    path.join(FUNCTION, "config", "tower"),
    path.join(FUNCTION, "enemy", "hpbar", "run"),
    path.join(FUNCTION, "enemy", "hpbar", "type"),
    path.join(FUNCTION, "enemy", "type"),
    path.join(FUNCTION, "shop", "give_item"),
    path.join(FUNCTION, "shop", "use"),
    path.join(FUNCTION, "spawn", "type"),
    path.join(FUNCTION, "tower", "attack", "run"),
    path.join(FUNCTION, "tower", "attack"),
    path.join(FUNCTION, "tower", "place_type"),
    path.join(FUNCTION, "tower", "select"),
    path.join(FUNCTION, "tower", "spawn"),
    path.join(FUNCTION, "tower", "tick"),
    path.join(FUNCTION, "tower", "type"),
    path.join(FUNCTION, "wave", "config"),
  ];
  const ownedFiles = [
    path.join(FUNCTION, "config", "core.mcfunction"),
    path.join(FUNCTION, "config", "economy.mcfunction"),
    path.join(FUNCTION, "team", "load.mcfunction"),
    path.join(FUNCTION, "wave", "run_config.mcfunction"),
  ];

  for (const directory of ownedDirs) {
    if (!fs.existsSync(directory)) {
      continue;
    }
    for (const entry of fs.readdirSync(directory, { withFileTypes: true })) {
      const filePath = path.join(directory, entry.name);
      if (entry.isFile() && entry.name.endsWith(".mcfunction") && generatedFile(filePath)) {
        fs.unlinkSync(filePath);
      }
    }
  }

  for (const filePath of ownedFiles) {
    if (generatedFile(filePath)) {
      fs.unlinkSync(filePath);
    }
  }
}

function validateTypeId(typeId, kind) {
  if (!TYPE_RE.test(typeId)) {
    throw new TdgenError(`Invalid ${kind} id '${typeId}'. Use lowercase letters, numbers, and underscores.`);
  }
}

function requireFields(spec, fields, label) {
  const missing = fields.filter((field) => !(field in spec));
  if (missing.length > 0) {
    throw new TdgenError(`${label} is missing required field(s): ${missing.join(", ")}`);
  }
}

function equipmentLines(equipment = []) {
  return equipment.map((item) => `item replace entity @s ${item.slot} with ${item.item}`);
}

function renderEnemyConfig(enemy) {
  const typeId = enemy.id;
  return [
    `# ${typeId} 적 설정입니다.`,
    `scoreboard players set ${scoreboardName("enemy", typeId, "hp")} td.enemy_max_hp ${enemy.hp}`,
    `scoreboard players set ${scoreboardName("enemy", typeId, "speed")} td.speed ${enemy.speed}`,
    `scoreboard players set ${scoreboardName("enemy", typeId, "reward")} td.reward ${enemy.reward}`,
    `scoreboard players set ${scoreboardName("enemy", typeId, "core_damage")} td.core_damage ${enemy.core_damage}`,
  ];
}

function renderEnemySpawn(enemy) {
  const typeId = enemy.id;
  const display = enemy.display_name;
  const color = enemy.custom_name_color ?? "white";
  const bold = enemy.bold ? ",bold:true" : "";
  const customName = `{text:${snbtString(display)},color:${snbtString(color)}${bold}}`;
  const nbt =
    `{Tags:["td.enemy","td.new","td.type.${typeId}"],` +
    "NoAI:1b,NoGravity:1b,PersistenceRequired:1b,Silent:1b," +
    `CustomName:${customName},CustomNameVisible:1b}`;
  return [
    `# 현재 위치에 ${typeId} 타입 적을 소환하고 초기화합니다.`,
    `summon ${enemy.entity} ~ ~ ~ ${nbt}`,
    "",
    `execute as @e[tag=td.new,tag=td.type.${typeId},sort=nearest,limit=1] at @s run function td:enemy/type/${typeId}`,
    `execute as @e[tag=td.new,tag=td.type.${typeId},sort=nearest,limit=1] at @s run function td:spawn/common`,
  ];
}

function renderEnemyType(enemy) {
  const typeId = enemy.id;
  const team = enemy.team.name;
  const lines = [
    `# ${typeId} 타입 설정입니다.`,
    `# HP, speed, reward, core damage는 td:config/enemy/${typeId}에서 가져옵니다.`,
    `tag @s add td.type.${typeId}`,
    `scoreboard players operation @s td.enemy_max_hp = ${scoreboardName("enemy", typeId, "hp")} td.enemy_max_hp`,
    `scoreboard players operation @s td.enemy_hp = ${scoreboardName("enemy", typeId, "hp")} td.enemy_max_hp`,
    `scoreboard players operation @s td.speed = ${scoreboardName("enemy", typeId, "speed")} td.speed`,
    `scoreboard players operation @s td.reward = ${scoreboardName("enemy", typeId, "reward")} td.reward`,
    `scoreboard players operation @s td.core_damage = ${scoreboardName("enemy", typeId, "core_damage")} td.core_damage`,
    "",
    "# 팀 색상과 충돌 방지 규칙을 적용합니다.",
    `team join ${team} @s`,
    "",
    `attribute @s minecraft:scale base set ${formatScale(enemy.scale)}`,
    "",
  ];
  lines.push(...equipmentLines(enemy.equipment ?? []));
  if (enemy.equipment?.length) {
    lines.push("");
  }
  lines.push(...(enemy.effects ?? []));
  return lines;
}

function renderEnemyHpbarType(enemy) {
  const name = enemy.display_name;
  const bold = (enemy.hpbar_bold ?? enemy.bold) ? ",bold:true" : "";
  const lines = [];
  for (let ratio = 10; ratio >= 1; ratio -= 1) {
    const full = "█".repeat(ratio);
    const empty = "░".repeat(10 - ratio);
    const text = `${name} ${ratio}/10 ${full}${empty}`;
    const color = HP_COLORS[ratio];
    lines.push(
      `execute if score @s td.hp_ratio matches ${ratio} run data merge entity @s ` +
        `{CustomNameVisible:1b,CustomName:{text:${snbtString(text)},color:${snbtString(color)}${bold}}}`,
    );
  }
  return lines;
}

function renderEnemyHpbarRun(enemy) {
  const typeId = enemy.id;
  return [
    `execute if entity @s[tag=td.type.${typeId}] run tag @s add td.hpbar.matched`,
    `execute if entity @s[tag=td.type.${typeId}] run function td:enemy/hpbar/type/${typeId}`,
  ];
}

function renderTowerConfig(tower) {
  const typeId = tower.id;
  return [
    `# ${typeId} 타워 설정입니다.`,
    `scoreboard players set ${scoreboardName("tower", typeId, "damage")} td.tmp ${tower.damage}`,
    `scoreboard players set ${scoreboardName("tower", typeId, "initial_cd")} td.tower_cd ${tower.initial_cooldown}`,
  ];
}

function renderShopGiveItem(tower) {
  const typeId = tower.id;
  const shop = tower.shop;
  const itemName = compactJson({ text: shop.item_name, color: shop.color ?? "white", italic: false });
  const lore = compactJson({ text: shop.lore ?? "Configured cost", color: "gray", italic: false });
  const glint = shop.glint ?? true ? "true" : "false";
  return [
    `give @s minecraft:carrot_on_a_stick[custom_data={td:{tool:"tower",tower:"${typeId}"}},item_name='${itemName}',lore=['${lore}'],enchantment_glint_override=${glint}] 1`,
  ];
}

function renderShopUse(tower) {
  const typeId = tower.id;
  return [
    `execute if items entity @s weapon.mainhand minecraft:carrot_on_a_stick[custom_data~{td:{tool:"tower",tower:"${typeId}"}}] run function td:tower/select/${typeId}`,
  ];
}

function renderTowerSelect(tower) {
  const typeId = tower.id;
  return [
    "tag @s add td.place.tower",
    `tag @s add td.place.${typeId}`,
    `scoreboard players operation @s td.place_cost = $tower_${typeId}_cost td.place_cost`,
  ];
}

function renderTowerSelectClear(towers) {
  return ["tag @s remove td.place.tower", ...towers.map((tower) => `tag @s remove td.place.${tower.id}`)];
}

function renderTowerPlaceType(tower) {
  const typeId = tower.id;
  return [`execute if entity @s[tag=td.place.${typeId}] run function td:tower/spawn/${typeId}`];
}

function renderTowerSpawn(tower) {
  const typeId = tower.id;
  const mannequin = tower.mannequin ?? {};
  const profile = mannequin.profile ?? { texture: "minecraft:entity/player/wide/steve", model: "wide" };
  const rotation = mannequin.rotation ?? [180, 0];
  const nbt =
    `{Tags:["td.tower","td.tower.${typeId}","td.tower.new"],` +
    "immovable:1b,NoGravity:1b,Invulnerable:1b,hide_description:1b,pose:\"standing\"," +
    `profile:{texture:"${profile.texture}",model:"${profile.model}"},` +
    `Rotation:[${rotation[0]}f,${rotation[1]}f]}`;
  const selector = `@e[type=minecraft:mannequin,tag=td.tower.new,tag=td.tower.${typeId},sort=nearest,limit=1]`;
  return [
    `# 현재 위치에 ${typeId} 방어 유닛을 실제 소환합니다. 비용 차감은 호출자가 처리합니다.`,
    `execute align xz positioned ~0.5 ~ ~0.5 run summon minecraft:mannequin ~ ~ ~ ${nbt}`,
    "",
    `scoreboard players set ${selector} td.owner_id 0`,
    `scoreboard players set ${selector} td.tower_cost 0`,
    `execute as ${selector} run scoreboard players operation @s td.owner_id = @a[tag=td.place.actor,limit=1] td.player_id`,
    `execute as ${selector} run scoreboard players operation @s td.tower_cost = @a[tag=td.place.actor,limit=1] td.place_cost`,
    `execute as ${selector} at @s run function td:tower/type/${typeId}`,
  ];
}

function renderTowerType(tower) {
  const typeId = tower.id;
  const lines = [
    `# ${typeId} 방어 유닛 설정입니다.`,
    `# 사거리 ${tower.range}, 공격 주기 ${tower.cooldown}틱입니다.`,
    `tag @s add td.tower.${typeId}`,
    `scoreboard players operation @s td.tower_cd = $tower_${typeId}_initial_cd td.tower_cd`,
    "function td:tower/assign_id",
    "",
    "team join td_tower @s",
    `attribute @s minecraft:scale base set ${formatScale(tower.scale)}`,
    "",
  ];
  lines.push(...equipmentLines(tower.equipment ?? []));
  if (tower.equipment?.length) {
    lines.push("");
  }
  lines.push(...(tower.effects ?? []));
  lines.push("", "tag @s remove td.tower.new");
  return lines;
}

function renderTowerTick(tower) {
  const typeId = tower.id;
  const attack = tower.attack;
  if (attack.preset === "raw" && "tick_lines" in attack) {
    return attack.tick_lines;
  }
  return [
    `execute as @e[type=minecraft:mannequin,tag=td.tower.${typeId},tag=!td.tower.blinking,scores={td.tower_cd=${tower.cooldown}..}] at @s if entity @e[tag=td.enemy,distance=..${tower.range},limit=1,sort=nearest] run function td:tower/attack/run/${typeId}`,
  ];
}

function renderTowerAttackRun(tower) {
  return ["function td:tower/clear_temp", `function td:tower/attack/${tower.id}`, "function td:tower/clear_temp"];
}

function renderTowerAttack(tower) {
  const preset = tower.attack.preset ?? "single";
  if (preset === "raw") {
    return tower.attack.lines ?? [];
  }
  if (preset === "single") {
    return renderTowerAttackSingle(tower);
  }
  if (preset === "splash") {
    return renderTowerAttackSplash(tower);
  }
  if (preset === "blink") {
    return renderTowerAttackBlink(tower);
  }
  throw new TdgenError(`Unknown tower attack preset for ${tower.id}: ${preset}`);
}

function renderTowerAttackSingle(tower) {
  const typeId = tower.id;
  return [
    `# ${typeId} 공격: 가장 가까운 적 하나에게 설정된 피해를 줍니다.`,
    "scoreboard players set @s td.tower_cd 0",
    "",
    `tag @e[tag=td.enemy,distance=..${tower.range},limit=1,sort=nearest] add td.tower.target`,
    "",
    "tp @s ~ ~ ~ facing entity @e[tag=td.tower.target,limit=1] eyes",
    "swing @s mainhand",
    "",
    "execute at @s positioned ^ ^1.2 ^1 run particle minecraft:sweep_attack ~ ~ ~ 0 0 0 0 1 force",
    "playsound minecraft:entity.player.attack.sweep master @a[distance=..16] ~ ~ ~ 0.7 1.15",
    "",
    `scoreboard players operation $damage td.tmp = $tower_${typeId}_damage td.tmp`,
    "execute as @e[tag=td.tower.target] at @s run function td:tower/damage/apply",
  ];
}

function renderTowerAttackSplash(tower) {
  const typeId = tower.id;
  const aoe = tower.attack.aoe ?? 2.5;
  return [
    `# ${typeId} 공격: 가장 가까운 적 주변 ${aoe}블록에 설정된 광역 피해를 줍니다.`,
    "scoreboard players set @s td.tower_cd 0",
    "",
    `tag @e[tag=td.enemy,distance=..${tower.range},limit=1,sort=nearest] add td.tower.target`,
    "",
    "tp @s ~ ~ ~ facing entity @e[tag=td.tower.target,limit=1] eyes",
    "swing @s mainhand",
    "",
    "execute at @e[tag=td.tower.target,limit=1] run particle minecraft:enchant ~ ~1 ~ 0.8 0.5 0.8 0.25 60 force",
    "execute at @e[tag=td.tower.target,limit=1] run particle minecraft:poof ~ ~0.8 ~ 0.8 0.25 0.8 0.03 24 force",
    "execute at @e[tag=td.tower.target,limit=1] run playsound minecraft:entity.evoker.cast_spell master @a[distance=..20] ~ ~ ~ 0.8 1.2",
    "",
    `execute at @e[tag=td.tower.target,limit=1] run tag @e[tag=td.enemy,distance=..${aoe}] add td.tower.hit`,
    `scoreboard players operation $damage td.tmp = $tower_${typeId}_damage td.tmp`,
    "function td:tower/damage/hit_tagged",
  ];
}

function renderTowerAttackBlink(tower) {
  const typeId = tower.id;
  const aoe = tower.attack.aoe ?? 3;
  const blinkTime = tower.attack.blink_time ?? 6;
  return [
    `# ${typeId} 공격: 타겟에게 순간이동해 주변 ${aoe}블록에 설정된 광역 피해를 준 뒤 잠시 후 원위치로 돌아옵니다.`,
    "scoreboard players set @s td.tower_cd 0",
    "",
    `tag @e[tag=td.enemy,distance=..${tower.range},limit=1,sort=nearest] add td.tower.target`,
    "tag @s add td.tower.active_blink",
    "tag @s add td.tower.blinking",
    "",
    "execute at @s run summon minecraft:marker ~ ~ ~ {Tags:[\"td.tower.origin\",\"td.tower.origin.new\"]}",
    "execute as @e[type=minecraft:marker,tag=td.tower.origin.new,sort=nearest,limit=1] run scoreboard players operation @s td.tower_id = @e[type=minecraft:mannequin,tag=td.tower.active_blink,limit=1] td.tower_id",
    "tag @e[type=minecraft:marker,tag=td.tower.origin.new] remove td.tower.origin.new",
    "",
    "data modify entity @s immovable set value 0b",
    `scoreboard players set @s td.blink_time ${blinkTime}`,
    "tp @s @e[tag=td.tower.target,limit=1]",
    "tp @s ~ ~ ~ facing entity @e[tag=td.tower.target,limit=1] eyes",
    "swing @s mainhand",
    "",
    "execute at @s run particle minecraft:portal ~ ~1 ~ 0.7 0.6 0.7 0.12 80 force",
    "execute at @s run particle minecraft:sweep_attack ~ ~1.1 ~ 0.3 0.2 0.3 0 2 force",
    "playsound minecraft:entity.enderman.teleport master @a[distance=..24] ~ ~ ~ 0.8 1.1",
    "",
    `execute at @s run tag @e[tag=td.enemy,distance=..${aoe}] add td.tower.hit`,
    `scoreboard players operation $damage td.tmp = $tower_${typeId}_damage td.tmp`,
    "function td:tower/damage/hit_tagged",
  ];
}

function renderConfigCore(game, lastWave) {
  return [
    "# 코어와 웨이브 진행 기본값입니다.",
    `scoreboard players set $core_hp td.hp ${game.core_hp}`,
    `scoreboard players set $wave_prep_ticks td.wave_prep ${game.wave_prep_ticks}`,
    `scoreboard players set $hp_scale td.tmp ${game.hp_scale}`,
    `scoreboard players set $last_wave td.wave ${lastWave}`,
  ];
}

function renderConfigEconomy(game, towers) {
  const lines = ["# 경제 기본값입니다.", `scoreboard players set $start_money td.money ${game.start_money}`];
  for (const tower of towers) {
    lines.push(`scoreboard players set $tower_${tower.id}_cost td.place_cost ${tower.cost}`);
  }
  lines.push(
    "",
    "# 웨이브 진행 중 타워 제거 환불은 구매가를 이 값으로 나눕니다. 기본 2 = 50%.",
    `scoreboard players set $combat_refund_divisor td.tmp ${game.combat_refund_divisor}`,
    "scoreboard players set $two td.tmp 2",
  );
  return lines;
}

function renderTeamLoad(game, enemies) {
  const lines = ["# 적 타입별 팀을 만들고 색상과 충돌 규칙을 설정합니다."];
  for (const enemy of enemies) {
    const team = enemy.team;
    lines.push(
      `team add ${team.name}`,
      `team modify ${team.name} color ${team.color}`,
      `team modify ${team.name} collisionRule ${team.collision_rule ?? "never"}`,
      "",
    );
  }
  const towerTeam = game.tower_team;
  lines.push(
    "# 방어 유닛은 적 경로와 플레이어 이동을 방해하지 않도록 충돌을 끕니다.",
    `team add ${towerTeam.name}`,
    `team modify ${towerTeam.name} color ${towerTeam.color}`,
    `team modify ${towerTeam.name} collisionRule ${towerTeam.collision_rule ?? "never"}`,
  );
  return lines;
}

function renderWaveConfig(wave) {
  const title = wave.title ?? `Wave ${formatWave(wave.number)}`;
  const lines = [`# Wave ${formatWave(wave.number)}: ${title}.`];
  const events = [...(wave.events ?? [])].sort((left, right) => left.tick - right.tick);
  for (const event of events) {
    const tick = event.tick;
    const mode = event.mode ?? "random";
    const typeId = event.type;
    let call;
    if (mode === "random") {
      call = `function td:spawn/random {type:"${typeId}"}`;
    } else if (mode === "from") {
      call = `function td:spawn/from {type:"${typeId}",id:${event.id}}`;
    } else if (mode === "all") {
      call = `function td:spawn/all {type:"${typeId}"}`;
    } else {
      throw new TdgenError(`Unknown wave spawn mode in wave ${wave.number}: ${mode}`);
    }
    lines.push(`execute if score $wave_time td.wave_time matches ${tick} run ${call}`);
  }
  lines.push(`execute if score $wave_time td.wave_time matches ${wave.complete_tick} run scoreboard players set $wave_done td.wave_done 1`);
  return lines;
}

function renderWaveRunConfig(waves) {
  const lines = ["# 현재 $wave 번호에 맞는 생성된 웨이브 스폰표를 실행합니다."];
  for (const wave of waves) {
    lines.push(`execute if score $wave td.wave matches ${wave.number} run function td:wave/config/wave_${formatWave(wave.number)}`);
  }
  return lines;
}

function build() {
  validateSpecs();
  const game = loadGame();
  const enemies = loadSpecs("enemies");
  const towers = loadSpecs("towers");
  const waves = loadSpecs("waves").sort((left, right) => left.number - right.number);
  const lastWave = waves.length > 0 ? Math.max(...waves.map((wave) => wave.number)) : 0;

  cleanGeneratedFiles();

  writeFunction("config/core", renderConfigCore(game, lastWave));
  writeFunction("config/economy", renderConfigEconomy(game, towers));
  writeFunction("team/load", renderTeamLoad(game, enemies));

  for (const enemy of enemies) {
    const typeId = enemy.id;
    writeFunction(`config/enemy/${typeId}`, renderEnemyConfig(enemy));
    writeFunction(`spawn/type/${typeId}`, renderEnemySpawn(enemy));
    writeFunction(`enemy/type/${typeId}`, renderEnemyType(enemy));
    writeFunction(`enemy/hpbar/type/${typeId}`, renderEnemyHpbarType(enemy));
    writeFunction(`enemy/hpbar/run/${typeId}`, renderEnemyHpbarRun(enemy));
  }

  for (const tower of towers) {
    const typeId = tower.id;
    writeFunction(`config/tower/${typeId}`, renderTowerConfig(tower));
    writeFunction(`shop/give_item/${typeId}`, renderShopGiveItem(tower));
    writeFunction(`shop/use/${typeId}`, renderShopUse(tower));
    writeFunction(`tower/select/${typeId}`, renderTowerSelect(tower));
    writeFunction(`tower/place_type/${typeId}`, renderTowerPlaceType(tower));
    writeFunction(`tower/spawn/${typeId}`, renderTowerSpawn(tower));
    writeFunction(`tower/type/${typeId}`, renderTowerType(tower));
    writeFunction(`tower/tick/${typeId}`, renderTowerTick(tower));
    writeFunction(`tower/attack/${typeId}`, renderTowerAttack(tower));
    writeFunction(`tower/attack/run/${typeId}`, renderTowerAttackRun(tower));
  }

  writeFunction("tower/select/clear", renderTowerSelectClear(towers));

  for (const wave of waves) {
    writeFunction(`wave/config/wave_${formatWave(wave.number)}`, renderWaveConfig(wave));
  }
  writeFunction("wave/run_config", renderWaveRunConfig(waves));

  writeTag("config/load", [
    ns("config/core"),
    ns("config/economy"),
    ...enemies.map((enemy) => ns(`config/enemy/${enemy.id}`)),
    ...towers.map((tower) => ns(`config/tower/${tower.id}`)),
  ]);
  writeTag("enemy/hpbar_types", enemies.map((enemy) => ns(`enemy/hpbar/run/${enemy.id}`)));
  writeTag("shop/give_items", [...towers.map((tower) => ns(`shop/give_item/${tower.id}`)), ns("shop/give_item/remove_tower")]);
  writeTag("shop/use_items", [...towers.map((tower) => ns(`shop/use/${tower.id}`)), ns("shop/use/remove_tower")]);
  writeTag("tower/place_types", towers.map((tower) => ns(`tower/place_type/${tower.id}`)));
  writeTag("tower/tick_types", towers.map((tower) => ns(`tower/tick/${tower.id}`)));
}

function validateSpecs() {
  const game = loadGame();
  if (Number(game.combat_refund_divisor) <= 0) {
    throw new TdgenError("combat_refund_divisor must be greater than 0.");
  }

  const enemies = loadSpecs("enemies");
  const towers = loadSpecs("towers");
  const waves = loadSpecs("waves");
  const enemyIds = new Set(enemies.map((enemy) => enemy.id));
  const towerIds = new Set(towers.map((tower) => tower.id));

  checkArchiveCollisions("enemies", enemyIds);
  checkArchiveCollisions("towers", towerIds);
  checkArchiveCollisions("waves", new Set(waves.map((wave) => `wave_${formatWave(wave.number)}`)));

  for (const enemy of enemies) {
    requireFields(enemy, ["id", "display_name", "entity", "hp", "speed", "reward", "core_damage", "team"], enemy._path ?? "enemy");
    validateTypeId(enemy.id, "enemy");
    if (enemy.team?.name == null) {
      throw new TdgenError(`Enemy ${enemy.id} needs team.name`);
    }
  }

  for (const tower of towers) {
    requireFields(tower, ["id", "display_name", "cost", "damage", "initial_cooldown", "range", "cooldown", "shop", "attack"], tower._path ?? "tower");
    validateTypeId(tower.id, "tower");
    const preset = tower.attack.preset ?? "single";
    if (!new Set(["single", "splash", "blink", "raw"]).has(preset)) {
      throw new TdgenError(`Tower ${tower.id} has unsupported attack preset: ${preset}`);
    }
  }

  const seenWaves = new Set();
  for (const wave of waves) {
    requireFields(wave, ["number", "complete_tick", "events"], wave._path ?? "wave");
    const number = Number(wave.number);
    if (seenWaves.has(number)) {
      throw new TdgenError(`Duplicate wave number: ${number}`);
    }
    seenWaves.add(number);
    for (const event of wave.events ?? []) {
      requireFields(event, ["tick", "type"], `wave ${number} event`);
      if (!enemyIds.has(event.type)) {
        throw new TdgenError(`Wave ${number} references missing enemy type: ${event.type}`);
      }
      const mode = event.mode ?? "random";
      if (!new Set(["random", "from", "all"]).has(mode)) {
        throw new TdgenError(`Wave ${number} has unsupported spawn mode: ${mode}`);
      }
      if (mode === "from" && !("id" in event)) {
        throw new TdgenError(`Wave ${number} from-spawn event needs id`);
      }
    }
  }
}

function checkArchiveCollisions(kind, activeIds) {
  const archiveDir = path.join(ARCHIVE, kind);
  if (!fs.existsSync(archiveDir)) {
    return;
  }
  for (const filePath of listJsonFiles(archiveDir)) {
    const itemId = path.basename(filePath, ".json");
    if (activeIds.has(itemId)) {
      throw new TdgenError(`${kind} spec exists in both active and archive: ${itemId}`);
    }
  }
}

function listSpecs(kind) {
  const kinds = kind === "all" ? ["enemies", "towers", "waves"] : [pluralKind(kind)];
  for (const current of kinds) {
    console.log(`[${current}]`);
    for (const spec of loadSpecs(current)) {
      const label = current === "waves" ? `wave_${formatWave(spec.number)}` : spec.id;
      console.log(`  active   ${label}`);
    }
    const archiveDir = path.join(ARCHIVE, current);
    if (fs.existsSync(archiveDir)) {
      for (const filePath of listJsonFiles(archiveDir)) {
        console.log(`  archived ${path.basename(filePath, ".json")}`);
      }
    }
  }
}

function pluralKind(kind) {
  const mapping = {
    enemy: "enemies",
    tower: "towers",
    wave: "waves",
    enemies: "enemies",
    towers: "towers",
    waves: "waves",
  };
  if (!(kind in mapping)) {
    throw new TdgenError(`Unsupported kind: ${kind}`);
  }
  return mapping[kind];
}

function activeSpecPath(kind, itemId) {
  const plural = pluralKind(kind);
  if (plural === "waves") {
    return path.join(SPEC, plural, `wave_${formatWave(parseWaveNumber(itemId))}.json`);
  }
  return path.join(SPEC, plural, `${itemId}.json`);
}

function archiveSpecPath(kind, itemId) {
  const plural = pluralKind(kind);
  if (plural === "waves") {
    return path.join(ARCHIVE, plural, `wave_${formatWave(parseWaveNumber(itemId))}.json`);
  }
  return path.join(ARCHIVE, plural, `${itemId}.json`);
}

function parseWaveNumber(value) {
  const text = String(value).startsWith("wave_") ? String(value).slice("wave_".length) : String(value);
  if (!/^\d+$/u.test(text)) {
    throw new TdgenError(`Invalid wave id: ${value}`);
  }
  return Number.parseInt(text, 10);
}

function formatWave(number) {
  return String(Number(number)).padStart(2, "0");
}

function addSpec(kind, itemId, source) {
  const src = activeSpecPath(kind, source);
  const dst = activeSpecPath(kind, itemId);
  if (fs.existsSync(dst)) {
    throw new TdgenError(`Spec already exists: ${rel(dst)}`);
  }
  if (!fs.existsSync(src)) {
    throw new TdgenError(`Source spec not found: ${rel(src)}`);
  }
  const spec = readJson(src);
  if (pluralKind(kind) === "waves") {
    const number = parseWaveNumber(itemId);
    spec.number = number;
    spec.title = `Copied wave ${formatWave(number)}`;
    spec.order = number;
  } else {
    validateTypeId(itemId, kind);
    spec.id = itemId;
    spec.display_name = titleName(itemId);
    if (pluralKind(kind) === "enemies") {
      spec.team.name = `td_enemy_${itemId}`;
    }
    if (pluralKind(kind) === "towers") {
      spec.shop.item_name = `${titleName(itemId)} Tower`;
    }
  }
  writeJson(dst, spec);
  build();
}

function titleName(typeId) {
  return String(typeId)
    .split("_")
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join(" ");
}

function deleteSpec(kind, itemId) {
  const src = activeSpecPath(kind, itemId);
  const dst = archiveSpecPath(kind, itemId);
  if (!fs.existsSync(src)) {
    throw new TdgenError(`Active spec not found: ${rel(src)}`);
  }
  if (fs.existsSync(dst)) {
    throw new TdgenError(`Archive spec already exists: ${rel(dst)}`);
  }
  fs.mkdirSync(path.dirname(dst), { recursive: true });
  fs.renameSync(src, dst);
  build();
}

function restoreSpec(kind, itemId) {
  const src = archiveSpecPath(kind, itemId);
  const dst = activeSpecPath(kind, itemId);
  if (!fs.existsSync(src)) {
    throw new TdgenError(`Archived spec not found: ${rel(src)}`);
  }
  if (fs.existsSync(dst)) {
    throw new TdgenError(`Active spec already exists: ${rel(dst)}`);
  }
  fs.mkdirSync(path.dirname(dst), { recursive: true });
  fs.renameSync(src, dst);
  build();
}

function rootHelp() {
  return `usage: tdgen.js [-h] {build,validate,list,add,delete,restore} ...

Generate BlackWoolTD datapack files from JSON specs.

positional arguments:
  {build,validate,list,add,delete,restore}

options:
  -h, --help            show this help message and exit`;
}

function subcommandHelp(command) {
  if (command === "list") {
    return `usage: tdgen.js list [-h] {all,enemy,tower,wave}

positional arguments:
  {all,enemy,tower,wave}

options:
  -h, --help            show this help message and exit`;
  }
  if (command === "add") {
    return `usage: tdgen.js add [-h] --from SOURCE {enemy,tower,wave} id

positional arguments:
  {enemy,tower,wave}
  id

options:
  -h, --help          show this help message and exit
  --from SOURCE`;
  }
  if (command === "delete" || command === "restore") {
    return `usage: tdgen.js ${command} [-h] {enemy,tower,wave} id

positional arguments:
  {enemy,tower,wave}
  id

options:
  -h, --help          show this help message and exit`;
  }
  return rootHelp();
}

function hasHelp(args) {
  return args.includes("-h") || args.includes("--help");
}

function requireChoice(value, choices, label) {
  if (!choices.includes(value)) {
    throw new TdgenError(`Invalid ${label}: ${value}`);
  }
}

function parseAddArgs(args) {
  const positional = [];
  let source = null;
  for (let index = 0; index < args.length; index += 1) {
    const arg = args[index];
    if (arg === "--from") {
      source = args[index + 1];
      index += 1;
    } else if (arg.startsWith("--from=")) {
      source = arg.slice("--from=".length);
    } else {
      positional.push(arg);
    }
  }
  if (positional.length !== 2 || !source) {
    throw new TdgenError("Usage: tdgen.js add {enemy,tower,wave} id --from SOURCE");
  }
  return { kind: positional[0], id: positional[1], source };
}

function main(argv = process.argv.slice(2)) {
  if (argv.length === 0 || hasHelp(argv)) {
    const command = argv.find((arg) => !arg.startsWith("-"));
    console.log(command ? subcommandHelp(command) : rootHelp());
    return 0;
  }

  try {
    const [command, ...args] = argv;
    if (command === "build") {
      build();
    } else if (command === "validate") {
      validateSpecs();
    } else if (command === "list") {
      if (args.length !== 1) {
        throw new TdgenError("Usage: tdgen.js list {all,enemy,tower,wave}");
      }
      requireChoice(args[0], ["all", "enemy", "tower", "wave"], "list kind");
      listSpecs(args[0]);
    } else if (command === "add") {
      const { kind, id, source } = parseAddArgs(args);
      requireChoice(kind, ["enemy", "tower", "wave"], "add kind");
      addSpec(kind, id, source);
    } else if (command === "delete") {
      if (args.length !== 2) {
        throw new TdgenError("Usage: tdgen.js delete {enemy,tower,wave} id");
      }
      requireChoice(args[0], ["enemy", "tower", "wave"], "delete kind");
      deleteSpec(args[0], args[1]);
    } else if (command === "restore") {
      if (args.length !== 2) {
        throw new TdgenError("Usage: tdgen.js restore {enemy,tower,wave} id");
      }
      requireChoice(args[0], ["enemy", "tower", "wave"], "restore kind");
      restoreSpec(args[0], args[1]);
    } else {
      throw new TdgenError(`Unknown command: ${command}`);
    }
    return 0;
  } catch (error) {
    if (error instanceof TdgenError) {
      console.error(`tdgen: ${error.message}`);
      return 1;
    }
    throw error;
  }
}

export {
  addSpec,
  activeSpecPath,
  archiveSpecPath,
  build,
  checkArchiveCollisions,
  cleanGeneratedFiles,
  deleteSpec,
  generatedFile,
  listSpecs,
  loadGame,
  loadSpecs,
  main,
  parseWaveNumber,
  pluralKind,
  readJson,
  restoreSpec,
  validateSpecs,
  writeFunction,
  writeJson,
  writeTag,
};

if (process.argv[1] && path.resolve(process.argv[1]) === THIS_FILE) {
  process.exitCode = main();
}
