#!/usr/bin/env python3
from __future__ import annotations

import argparse
import json
import re
import shutil
import sys
from pathlib import Path
from typing import Any


ROOT = Path(__file__).resolve().parents[1]
DATA = ROOT / "data" / "td"
FUNCTION = DATA / "function"
TAG = DATA / "tags" / "function"
SPEC = ROOT / "tools" / "spec"
ARCHIVE = SPEC / "archive"

GENERATED = "# Generated by tools/tdgen.py. Do not edit directly."
TYPE_RE = re.compile(r"^[a-z0-9_]+$")
HP_COLORS = {
    10: "green",
    9: "green",
    8: "green",
    7: "yellow",
    6: "yellow",
    5: "yellow",
    4: "gold",
    3: "gold",
    2: "red",
    1: "dark_red",
}


class TdgenError(Exception):
    pass


def read_json(path: Path) -> Any:
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except FileNotFoundError as exc:
        raise TdgenError(f"Missing spec file: {path}") from exc
    except json.JSONDecodeError as exc:
        raise TdgenError(f"Invalid JSON in {path}: {exc}") from exc


def write_json(path: Path, value: Any) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(value, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")


def write_function(rel_path: str, lines: list[str]) -> None:
    path = FUNCTION / f"{rel_path}.mcfunction"
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join([GENERATED, *lines]).rstrip() + "\n", encoding="utf-8")


def write_tag(rel_path: str, values: list[str]) -> None:
    write_json(TAG / f"{rel_path}.json", {"values": values})


def ns(path: str) -> str:
    return f"td:{path}"


def load_specs(kind: str) -> list[dict[str, Any]]:
    specs: list[dict[str, Any]] = []
    for path in sorted((SPEC / kind).glob("*.json")):
        value = read_json(path)
        if value.get("enabled", True):
            value["_path"] = str(path.relative_to(ROOT))
            specs.append(value)
    return sorted(specs, key=lambda item: (item.get("order", 1000), item.get("id", item.get("number", 0))))


def load_game() -> dict[str, Any]:
    game = read_json(SPEC / "game.json")
    return {
        "core_hp": game.get("core_hp", 20),
        "wave_prep_ticks": game.get("wave_prep_ticks", 600),
        "hp_scale": game.get("hp_scale", 10),
        "start_money": game.get("start_money", 60),
        "combat_refund_divisor": game.get("combat_refund_divisor", 2),
        "tower_team": game.get("tower_team", {"name": "td_tower", "color": "blue", "collision_rule": "never"}),
    }


def compact_json(value: Any) -> str:
    return json.dumps(value, ensure_ascii=False, separators=(",", ":"))


def snbt_string(value: str) -> str:
    return "'" + value.replace("\\", "\\\\").replace("'", "\\'") + "'"


def scoreboard_name(prefix: str, type_id: str, suffix: str) -> str:
    return f"${prefix}_{type_id}_{suffix}"


def generated_file(path: Path) -> bool:
    if not path.exists() or not path.is_file():
        return False
    try:
        return path.read_text(encoding="utf-8").splitlines()[0] == GENERATED
    except IndexError:
        return False


def clean_generated_files() -> None:
    owned_dirs = [
        FUNCTION / "config" / "enemy",
        FUNCTION / "config" / "tower",
        FUNCTION / "enemy" / "hpbar" / "run",
        FUNCTION / "enemy" / "hpbar" / "type",
        FUNCTION / "enemy" / "type",
        FUNCTION / "shop" / "give_item",
        FUNCTION / "shop" / "use",
        FUNCTION / "spawn" / "type",
        FUNCTION / "tower" / "attack" / "run",
        FUNCTION / "tower" / "attack",
        FUNCTION / "tower" / "place_type",
        FUNCTION / "tower" / "select",
        FUNCTION / "tower" / "spawn",
        FUNCTION / "tower" / "tick",
        FUNCTION / "tower" / "type",
        FUNCTION / "wave" / "config",
    ]
    owned_files = [
        FUNCTION / "config" / "core.mcfunction",
        FUNCTION / "config" / "economy.mcfunction",
        FUNCTION / "team" / "load.mcfunction",
        FUNCTION / "wave" / "run_config.mcfunction",
    ]
    for directory in owned_dirs:
        if not directory.exists():
            continue
        for path in directory.glob("*.mcfunction"):
            if generated_file(path):
                path.unlink()
    for path in owned_files:
        if generated_file(path):
            path.unlink()


def validate_type_id(type_id: str, kind: str) -> None:
    if not TYPE_RE.match(type_id):
        raise TdgenError(f"Invalid {kind} id '{type_id}'. Use lowercase letters, numbers, and underscores.")


def require_fields(spec: dict[str, Any], fields: list[str], label: str) -> None:
    missing = [field for field in fields if field not in spec]
    if missing:
        raise TdgenError(f"{label} is missing required field(s): {', '.join(missing)}")


def equipment_lines(equipment: list[dict[str, str]]) -> list[str]:
    lines = []
    for item in equipment:
        lines.append(f"item replace entity @s {item['slot']} with {item['item']}")
    return lines


def render_enemy_config(enemy: dict[str, Any]) -> list[str]:
    type_id = enemy["id"]
    return [
        f"# {type_id} 적 설정입니다.",
        f"scoreboard players set {scoreboard_name('enemy', type_id, 'hp')} td.enemy_max_hp {enemy['hp']}",
        f"scoreboard players set {scoreboard_name('enemy', type_id, 'speed')} td.speed {enemy['speed']}",
        f"scoreboard players set {scoreboard_name('enemy', type_id, 'reward')} td.reward {enemy['reward']}",
        f"scoreboard players set {scoreboard_name('enemy', type_id, 'core_damage')} td.core_damage {enemy['core_damage']}",
    ]


def render_enemy_spawn(enemy: dict[str, Any]) -> list[str]:
    type_id = enemy["id"]
    display = enemy["display_name"]
    color = enemy.get("custom_name_color", "white")
    bold = ",bold:true" if enemy.get("bold", False) else ""
    custom_name = f"{{text:{snbt_string(display)},color:{snbt_string(color)}{bold}}}"
    nbt = (
        f'{{Tags:["td.enemy","td.new","td.type.{type_id}"],'
        f"NoAI:1b,NoGravity:1b,PersistenceRequired:1b,Silent:1b,"
        f"CustomName:{custom_name},CustomNameVisible:1b}}"
    )
    return [
        f"# 현재 위치에 {type_id} 타입 적을 소환하고 초기화합니다.",
        f"summon {enemy['entity']} ~ ~ ~ {nbt}",
        "",
        f"execute as @e[tag=td.new,tag=td.type.{type_id},sort=nearest,limit=1] at @s run function td:enemy/type/{type_id}",
        f"execute as @e[tag=td.new,tag=td.type.{type_id},sort=nearest,limit=1] at @s run function td:spawn/common",
    ]


def render_enemy_type(enemy: dict[str, Any]) -> list[str]:
    type_id = enemy["id"]
    team = enemy["team"]["name"]
    lines = [
        f"# {type_id} 타입 설정입니다.",
        f"# HP, speed, reward, core damage는 td:config/enemy/{type_id}에서 가져옵니다.",
        f"tag @s add td.type.{type_id}",
        f"scoreboard players operation @s td.enemy_max_hp = {scoreboard_name('enemy', type_id, 'hp')} td.enemy_max_hp",
        f"scoreboard players operation @s td.enemy_hp = {scoreboard_name('enemy', type_id, 'hp')} td.enemy_max_hp",
        f"scoreboard players operation @s td.speed = {scoreboard_name('enemy', type_id, 'speed')} td.speed",
        f"scoreboard players operation @s td.reward = {scoreboard_name('enemy', type_id, 'reward')} td.reward",
        f"scoreboard players operation @s td.core_damage = {scoreboard_name('enemy', type_id, 'core_damage')} td.core_damage",
        "",
        "# 팀 색상과 충돌 방지 규칙을 적용합니다.",
        f"team join {team} @s",
        "",
        f"attribute @s minecraft:scale base set {enemy.get('scale', 1.0)}",
        "",
    ]
    lines.extend(equipment_lines(enemy.get("equipment", [])))
    if enemy.get("equipment"):
        lines.append("")
    lines.extend(enemy.get("effects", []))
    return lines


def render_enemy_hpbar_type(enemy: dict[str, Any]) -> list[str]:
    name = enemy["display_name"]
    bold = ",bold:true" if enemy.get("hpbar_bold", enemy.get("bold", False)) else ""
    lines: list[str] = []
    for ratio in range(10, 0, -1):
        full = "█" * ratio
        empty = "░" * (10 - ratio)
        text = f"{name} {ratio}/10 {full}{empty}"
        color = HP_COLORS[ratio]
        lines.append(
            f"execute if score @s td.hp_ratio matches {ratio} run data merge entity @s "
            f"{{CustomNameVisible:1b,CustomName:{{text:{snbt_string(text)},color:{snbt_string(color)}{bold}}}}}"
        )
    return lines


def render_enemy_hpbar_run(enemy: dict[str, Any]) -> list[str]:
    type_id = enemy["id"]
    return [
        f"execute if entity @s[tag=td.type.{type_id}] run tag @s add td.hpbar.matched",
        f"execute if entity @s[tag=td.type.{type_id}] run function td:enemy/hpbar/type/{type_id}",
    ]


def render_tower_config(tower: dict[str, Any]) -> list[str]:
    type_id = tower["id"]
    return [
        f"# {type_id} 타워 설정입니다.",
        f"scoreboard players set {scoreboard_name('tower', type_id, 'damage')} td.tmp {tower['damage']}",
        f"scoreboard players set {scoreboard_name('tower', type_id, 'initial_cd')} td.tower_cd {tower['initial_cooldown']}",
    ]


def render_shop_give_item(tower: dict[str, Any]) -> list[str]:
    type_id = tower["id"]
    shop = tower["shop"]
    item_name = compact_json({"text": shop["item_name"], "color": shop.get("color", "white"), "italic": False})
    lore = compact_json({"text": shop.get("lore", "Configured cost"), "color": "gray", "italic": False})
    glint = "true" if shop.get("glint", True) else "false"
    return [
        f"give @s minecraft:carrot_on_a_stick[custom_data={{td:{{tool:\"tower\",tower:\"{type_id}\"}}}},item_name='{item_name}',lore=['{lore}'],enchantment_glint_override={glint}] 1"
    ]


def render_shop_use(tower: dict[str, Any]) -> list[str]:
    type_id = tower["id"]
    return [
        f"execute if items entity @s weapon.mainhand minecraft:carrot_on_a_stick[custom_data~{{td:{{tool:\"tower\",tower:\"{type_id}\"}}}}] run function td:tower/select/{type_id}"
    ]


def render_tower_select(tower: dict[str, Any]) -> list[str]:
    type_id = tower["id"]
    return [
        "tag @s add td.place.tower",
        f"tag @s add td.place.{type_id}",
        f"scoreboard players operation @s td.place_cost = $tower_{type_id}_cost td.place_cost",
    ]


def render_tower_select_clear(towers: list[dict[str, Any]]) -> list[str]:
    lines = ["tag @s remove td.place.tower"]
    lines.extend(f"tag @s remove td.place.{tower['id']}" for tower in towers)
    return lines


def render_tower_place_type(tower: dict[str, Any]) -> list[str]:
    type_id = tower["id"]
    return [f"execute if entity @s[tag=td.place.{type_id}] run function td:tower/spawn/{type_id}"]


def render_tower_spawn(tower: dict[str, Any]) -> list[str]:
    type_id = tower["id"]
    mannequin = tower.get("mannequin", {})
    profile = mannequin.get("profile", {"texture": "minecraft:entity/player/wide/steve", "model": "wide"})
    rotation = mannequin.get("rotation", [180, 0])
    nbt = (
        f'{{Tags:["td.tower","td.tower.{type_id}","td.tower.new"],'
        f'immovable:1b,NoGravity:1b,Invulnerable:1b,hide_description:1b,pose:"standing",'
        f'profile:{{texture:"{profile["texture"]}",model:"{profile["model"]}"}},'
        f"Rotation:[{rotation[0]}f,{rotation[1]}f]}}"
    )
    selector = f"@e[type=minecraft:mannequin,tag=td.tower.new,tag=td.tower.{type_id},sort=nearest,limit=1]"
    return [
        f"# 현재 위치에 {type_id} 방어 유닛을 실제 소환합니다. 비용 차감은 호출자가 처리합니다.",
        f"execute align xz positioned ~0.5 ~ ~0.5 run summon minecraft:mannequin ~ ~ ~ {nbt}",
        "",
        f"scoreboard players set {selector} td.owner_id 0",
        f"scoreboard players set {selector} td.tower_cost 0",
        f"execute as {selector} run scoreboard players operation @s td.owner_id = @a[tag=td.place.actor,limit=1] td.player_id",
        f"execute as {selector} run scoreboard players operation @s td.tower_cost = @a[tag=td.place.actor,limit=1] td.place_cost",
        f"execute as {selector} at @s run function td:tower/type/{type_id}",
    ]


def render_tower_type(tower: dict[str, Any]) -> list[str]:
    type_id = tower["id"]
    lines = [
        f"# {type_id} 방어 유닛 설정입니다.",
        f"# 사거리 {tower['range']}, 공격 주기 {tower['cooldown']}틱입니다.",
        f"tag @s add td.tower.{type_id}",
        f"scoreboard players operation @s td.tower_cd = $tower_{type_id}_initial_cd td.tower_cd",
        "function td:tower/assign_id",
        "",
        "team join td_tower @s",
        f"attribute @s minecraft:scale base set {tower.get('scale', 1.0)}",
        "",
    ]
    lines.extend(equipment_lines(tower.get("equipment", [])))
    if tower.get("equipment"):
        lines.append("")
    lines.extend(tower.get("effects", []))
    lines.extend(["", "tag @s remove td.tower.new"])
    return lines


def render_tower_tick(tower: dict[str, Any]) -> list[str]:
    type_id = tower["id"]
    attack = tower["attack"]
    if attack.get("preset") == "raw" and "tick_lines" in attack:
        return attack["tick_lines"]
    return [
        f"execute as @e[type=minecraft:mannequin,tag=td.tower.{type_id},tag=!td.tower.blinking,scores={{td.tower_cd={tower['cooldown']}..}}] at @s if entity @e[tag=td.enemy,distance=..{tower['range']},limit=1,sort=nearest] run function td:tower/attack/run/{type_id}"
    ]


def render_tower_attack_run(tower: dict[str, Any]) -> list[str]:
    type_id = tower["id"]
    return [
        "function td:tower/clear_temp",
        f"function td:tower/attack/{type_id}",
        "function td:tower/clear_temp",
    ]


def render_tower_attack(tower: dict[str, Any]) -> list[str]:
    type_id = tower["id"]
    attack = tower["attack"]
    preset = attack.get("preset", "single")
    if preset == "raw":
        return attack.get("lines", [])
    if preset == "single":
        return render_tower_attack_single(tower)
    if preset == "splash":
        return render_tower_attack_splash(tower)
    if preset == "blink":
        return render_tower_attack_blink(tower)
    raise TdgenError(f"Unknown tower attack preset for {type_id}: {preset}")


def render_tower_attack_single(tower: dict[str, Any]) -> list[str]:
    type_id = tower["id"]
    return [
        f"# {type_id} 공격: 가장 가까운 적 하나에게 설정된 피해를 줍니다.",
        "scoreboard players set @s td.tower_cd 0",
        "",
        f"tag @e[tag=td.enemy,distance=..{tower['range']},limit=1,sort=nearest] add td.tower.target",
        "",
        "tp @s ~ ~ ~ facing entity @e[tag=td.tower.target,limit=1] eyes",
        "swing @s mainhand",
        "",
        "execute at @s positioned ^ ^1.2 ^1 run particle minecraft:sweep_attack ~ ~ ~ 0 0 0 0 1 force",
        "playsound minecraft:entity.player.attack.sweep master @a[distance=..16] ~ ~ ~ 0.7 1.15",
        "",
        f"scoreboard players operation $damage td.tmp = $tower_{type_id}_damage td.tmp",
        "execute as @e[tag=td.tower.target] at @s run function td:tower/damage/apply",
    ]


def render_tower_attack_splash(tower: dict[str, Any]) -> list[str]:
    type_id = tower["id"]
    aoe = tower["attack"].get("aoe", 2.5)
    return [
        f"# {type_id} 공격: 가장 가까운 적 주변 {aoe}블록에 설정된 광역 피해를 줍니다.",
        "scoreboard players set @s td.tower_cd 0",
        "",
        f"tag @e[tag=td.enemy,distance=..{tower['range']},limit=1,sort=nearest] add td.tower.target",
        "",
        "tp @s ~ ~ ~ facing entity @e[tag=td.tower.target,limit=1] eyes",
        "swing @s mainhand",
        "",
        "execute at @e[tag=td.tower.target,limit=1] run particle minecraft:enchant ~ ~1 ~ 0.8 0.5 0.8 0.25 60 force",
        "execute at @e[tag=td.tower.target,limit=1] run particle minecraft:poof ~ ~0.8 ~ 0.8 0.25 0.8 0.03 24 force",
        "execute at @e[tag=td.tower.target,limit=1] run playsound minecraft:entity.evoker.cast_spell master @a[distance=..20] ~ ~ ~ 0.8 1.2",
        "",
        f"execute at @e[tag=td.tower.target,limit=1] run tag @e[tag=td.enemy,distance=..{aoe}] add td.tower.hit",
        f"scoreboard players operation $damage td.tmp = $tower_{type_id}_damage td.tmp",
        "function td:tower/damage/hit_tagged",
    ]


def render_tower_attack_blink(tower: dict[str, Any]) -> list[str]:
    type_id = tower["id"]
    aoe = tower["attack"].get("aoe", 3)
    blink_time = tower["attack"].get("blink_time", 6)
    return [
        f"# {type_id} 공격: 타겟에게 순간이동해 주변 {aoe}블록에 설정된 광역 피해를 준 뒤 잠시 후 원위치로 돌아옵니다.",
        "scoreboard players set @s td.tower_cd 0",
        "",
        f"tag @e[tag=td.enemy,distance=..{tower['range']},limit=1,sort=nearest] add td.tower.target",
        "tag @s add td.tower.active_blink",
        "tag @s add td.tower.blinking",
        "",
        'execute at @s run summon minecraft:marker ~ ~ ~ {Tags:["td.tower.origin","td.tower.origin.new"]}',
        "execute as @e[type=minecraft:marker,tag=td.tower.origin.new,sort=nearest,limit=1] run scoreboard players operation @s td.tower_id = @e[type=minecraft:mannequin,tag=td.tower.active_blink,limit=1] td.tower_id",
        "tag @e[type=minecraft:marker,tag=td.tower.origin.new] remove td.tower.origin.new",
        "",
        "data modify entity @s immovable set value 0b",
        f"scoreboard players set @s td.blink_time {blink_time}",
        "tp @s @e[tag=td.tower.target,limit=1]",
        "tp @s ~ ~ ~ facing entity @e[tag=td.tower.target,limit=1] eyes",
        "swing @s mainhand",
        "",
        "execute at @s run particle minecraft:portal ~ ~1 ~ 0.7 0.6 0.7 0.12 80 force",
        "execute at @s run particle minecraft:sweep_attack ~ ~1.1 ~ 0.3 0.2 0.3 0 2 force",
        "playsound minecraft:entity.enderman.teleport master @a[distance=..24] ~ ~ ~ 0.8 1.1",
        "",
        f"execute at @s run tag @e[tag=td.enemy,distance=..{aoe}] add td.tower.hit",
        f"scoreboard players operation $damage td.tmp = $tower_{type_id}_damage td.tmp",
        "function td:tower/damage/hit_tagged",
    ]


def render_config_core(game: dict[str, Any], last_wave: int) -> list[str]:
    return [
        "# 코어와 웨이브 진행 기본값입니다.",
        f"scoreboard players set $core_hp td.hp {game['core_hp']}",
        f"scoreboard players set $wave_prep_ticks td.wave_prep {game['wave_prep_ticks']}",
        f"scoreboard players set $hp_scale td.tmp {game['hp_scale']}",
        f"scoreboard players set $last_wave td.wave {last_wave}",
    ]


def render_config_economy(game: dict[str, Any], towers: list[dict[str, Any]]) -> list[str]:
    lines = [
        "# 경제 기본값입니다.",
        f"scoreboard players set $start_money td.money {game['start_money']}",
    ]
    for tower in towers:
        lines.append(f"scoreboard players set $tower_{tower['id']}_cost td.place_cost {tower['cost']}")
    lines.extend(
        [
            "",
            "# 웨이브 진행 중 타워 제거 환불은 구매가를 이 값으로 나눕니다. 기본 2 = 50%.",
            f"scoreboard players set $combat_refund_divisor td.tmp {game['combat_refund_divisor']}",
            "scoreboard players set $two td.tmp 2",
        ]
    )
    return lines


def render_team_load(game: dict[str, Any], enemies: list[dict[str, Any]]) -> list[str]:
    lines = ["# 적 타입별 팀을 만들고 색상과 충돌 규칙을 설정합니다."]
    for enemy in enemies:
        team = enemy["team"]
        lines.extend(
            [
                f"team add {team['name']}",
                f"team modify {team['name']} color {team['color']}",
                f"team modify {team['name']} collisionRule {team.get('collision_rule', 'never')}",
                "",
            ]
        )
    tower_team = game["tower_team"]
    lines.extend(
        [
            "# 방어 유닛은 적 경로와 플레이어 이동을 방해하지 않도록 충돌을 끕니다.",
            f"team add {tower_team['name']}",
            f"team modify {tower_team['name']} color {tower_team['color']}",
            f"team modify {tower_team['name']} collisionRule {tower_team.get('collision_rule', 'never')}",
        ]
    )
    return lines


def render_wave_config(wave: dict[str, Any]) -> list[str]:
    title = wave.get("title", f"Wave {wave['number']:02d}")
    lines = [f"# Wave {wave['number']:02d}: {title}."]
    for event in sorted(wave.get("events", []), key=lambda item: item["tick"]):
        tick = event["tick"]
        mode = event.get("mode", "random")
        type_id = event["type"]
        if mode == "random":
            call = f'function td:spawn/random {{type:"{type_id}"}}'
        elif mode == "from":
            call = f'function td:spawn/from {{type:"{type_id}",id:{event["id"]}}}'
        elif mode == "all":
            call = f'function td:spawn/all {{type:"{type_id}"}}'
        else:
            raise TdgenError(f"Unknown wave spawn mode in wave {wave['number']}: {mode}")
        lines.append(f"execute if score $wave_time td.wave_time matches {tick} run {call}")
    lines.append(
        f"execute if score $wave_time td.wave_time matches {wave['complete_tick']} run scoreboard players set $wave_done td.wave_done 1"
    )
    return lines


def render_wave_run_config(waves: list[dict[str, Any]]) -> list[str]:
    lines = ["# 현재 $wave 번호에 맞는 생성된 웨이브 스폰표를 실행합니다."]
    for wave in waves:
        number = wave["number"]
        lines.append(f"execute if score $wave td.wave matches {number} run function td:wave/config/wave_{number:02d}")
    return lines


def build() -> None:
    validate_specs()
    game = load_game()
    enemies = load_specs("enemies")
    towers = load_specs("towers")
    waves = sorted(load_specs("waves"), key=lambda item: item["number"])
    last_wave = max((wave["number"] for wave in waves), default=0)

    clean_generated_files()

    write_function("config/core", render_config_core(game, last_wave))
    write_function("config/economy", render_config_economy(game, towers))
    write_function("team/load", render_team_load(game, enemies))

    for enemy in enemies:
        type_id = enemy["id"]
        write_function(f"config/enemy/{type_id}", render_enemy_config(enemy))
        write_function(f"spawn/type/{type_id}", render_enemy_spawn(enemy))
        write_function(f"enemy/type/{type_id}", render_enemy_type(enemy))
        write_function(f"enemy/hpbar/type/{type_id}", render_enemy_hpbar_type(enemy))
        write_function(f"enemy/hpbar/run/{type_id}", render_enemy_hpbar_run(enemy))

    for tower in towers:
        type_id = tower["id"]
        write_function(f"config/tower/{type_id}", render_tower_config(tower))
        write_function(f"shop/give_item/{type_id}", render_shop_give_item(tower))
        write_function(f"shop/use/{type_id}", render_shop_use(tower))
        write_function(f"tower/select/{type_id}", render_tower_select(tower))
        write_function(f"tower/place_type/{type_id}", render_tower_place_type(tower))
        write_function(f"tower/spawn/{type_id}", render_tower_spawn(tower))
        write_function(f"tower/type/{type_id}", render_tower_type(tower))
        write_function(f"tower/tick/{type_id}", render_tower_tick(tower))
        write_function(f"tower/attack/{type_id}", render_tower_attack(tower))
        write_function(f"tower/attack/run/{type_id}", render_tower_attack_run(tower))

    write_function("tower/select/clear", render_tower_select_clear(towers))

    for wave in waves:
        write_function(f"wave/config/wave_{wave['number']:02d}", render_wave_config(wave))
    write_function("wave/run_config", render_wave_run_config(waves))

    write_tag("config/load", [ns("config/core"), ns("config/economy"), *[ns(f"config/enemy/{e['id']}") for e in enemies], *[ns(f"config/tower/{t['id']}") for t in towers]])
    write_tag("enemy/hpbar_types", [ns(f"enemy/hpbar/run/{enemy['id']}") for enemy in enemies])
    write_tag("shop/give_items", [*[ns(f"shop/give_item/{tower['id']}") for tower in towers], ns("shop/give_item/remove_tower")])
    write_tag("shop/use_items", [*[ns(f"shop/use/{tower['id']}") for tower in towers], ns("shop/use/remove_tower")])
    write_tag("tower/place_types", [ns(f"tower/place_type/{tower['id']}") for tower in towers])
    write_tag("tower/tick_types", [ns(f"tower/tick/{tower['id']}") for tower in towers])


def validate_specs() -> None:
    game = load_game()
    if int(game["combat_refund_divisor"]) <= 0:
        raise TdgenError("combat_refund_divisor must be greater than 0.")

    enemies = load_specs("enemies")
    towers = load_specs("towers")
    waves = load_specs("waves")
    enemy_ids = {enemy["id"] for enemy in enemies}
    tower_ids = {tower["id"] for tower in towers}

    check_archive_collisions("enemies", enemy_ids)
    check_archive_collisions("towers", tower_ids)
    check_archive_collisions("waves", {f"wave_{wave['number']:02d}" for wave in waves})

    for enemy in enemies:
        require_fields(enemy, ["id", "display_name", "entity", "hp", "speed", "reward", "core_damage", "team"], enemy.get("_path", "enemy"))
        validate_type_id(enemy["id"], "enemy")
        if enemy["team"].get("name") is None:
            raise TdgenError(f"Enemy {enemy['id']} needs team.name")

    for tower in towers:
        require_fields(tower, ["id", "display_name", "cost", "damage", "initial_cooldown", "range", "cooldown", "shop", "attack"], tower.get("_path", "tower"))
        validate_type_id(tower["id"], "tower")
        preset = tower["attack"].get("preset", "single")
        if preset not in {"single", "splash", "blink", "raw"}:
            raise TdgenError(f"Tower {tower['id']} has unsupported attack preset: {preset}")

    seen_waves: set[int] = set()
    for wave in waves:
        require_fields(wave, ["number", "complete_tick", "events"], wave.get("_path", "wave"))
        number = int(wave["number"])
        if number in seen_waves:
            raise TdgenError(f"Duplicate wave number: {number}")
        seen_waves.add(number)
        for event in wave.get("events", []):
            require_fields(event, ["tick", "type"], f"wave {number} event")
            if event["type"] not in enemy_ids:
                raise TdgenError(f"Wave {number} references missing enemy type: {event['type']}")
            mode = event.get("mode", "random")
            if mode not in {"random", "from", "all"}:
                raise TdgenError(f"Wave {number} has unsupported spawn mode: {mode}")
            if mode == "from" and "id" not in event:
                raise TdgenError(f"Wave {number} from-spawn event needs id")


def check_archive_collisions(kind: str, active_ids: set[str]) -> None:
    archive_dir = ARCHIVE / kind
    if not archive_dir.exists():
        return
    for path in archive_dir.glob("*.json"):
        item_id = path.stem
        if kind == "waves":
            item_id = path.stem
        if item_id in active_ids:
            raise TdgenError(f"{kind} spec exists in both active and archive: {item_id}")


def list_specs(kind: str) -> None:
    kinds = ["enemies", "towers", "waves"] if kind == "all" else [plural_kind(kind)]
    for current in kinds:
        print(f"[{current}]")
        for spec in load_specs(current):
            label = f"wave_{spec['number']:02d}" if current == "waves" else spec["id"]
            print(f"  active   {label}")
        archive_dir = ARCHIVE / current
        if archive_dir.exists():
            for path in sorted(archive_dir.glob("*.json")):
                print(f"  archived {path.stem}")


def plural_kind(kind: str) -> str:
    mapping = {"enemy": "enemies", "tower": "towers", "wave": "waves", "enemies": "enemies", "towers": "towers", "waves": "waves"}
    if kind not in mapping:
        raise TdgenError(f"Unsupported kind: {kind}")
    return mapping[kind]


def active_spec_path(kind: str, item_id: str) -> Path:
    plural = plural_kind(kind)
    if plural == "waves":
        number = parse_wave_number(item_id)
        return SPEC / plural / f"wave_{number:02d}.json"
    return SPEC / plural / f"{item_id}.json"


def archive_spec_path(kind: str, item_id: str) -> Path:
    plural = plural_kind(kind)
    if plural == "waves":
        number = parse_wave_number(item_id)
        return ARCHIVE / plural / f"wave_{number:02d}.json"
    return ARCHIVE / plural / f"{item_id}.json"


def parse_wave_number(value: str) -> int:
    text = value.removeprefix("wave_")
    try:
        return int(text)
    except ValueError as exc:
        raise TdgenError(f"Invalid wave id: {value}") from exc


def add_spec(kind: str, item_id: str, source: str) -> None:
    src = active_spec_path(kind, source)
    dst = active_spec_path(kind, item_id)
    if dst.exists():
        raise TdgenError(f"Spec already exists: {dst}")
    if not src.exists():
        raise TdgenError(f"Source spec not found: {src}")
    spec = read_json(src)
    if plural_kind(kind) == "waves":
        number = parse_wave_number(item_id)
        spec["number"] = number
        spec["title"] = f"Copied wave {number:02d}"
        spec["order"] = number
    else:
        validate_type_id(item_id, kind)
        spec["id"] = item_id
        spec["display_name"] = title_name(item_id)
        if plural_kind(kind) == "enemies":
            spec["team"]["name"] = f"td_enemy_{item_id}"
        if plural_kind(kind) == "towers":
            spec["shop"]["item_name"] = f"{title_name(item_id)} Tower"
    write_json(dst, spec)
    build()


def title_name(type_id: str) -> str:
    return " ".join(part.capitalize() for part in type_id.split("_"))


def delete_spec(kind: str, item_id: str) -> None:
    src = active_spec_path(kind, item_id)
    dst = archive_spec_path(kind, item_id)
    if not src.exists():
        raise TdgenError(f"Active spec not found: {src}")
    if dst.exists():
        raise TdgenError(f"Archive spec already exists: {dst}")
    dst.parent.mkdir(parents=True, exist_ok=True)
    shutil.move(str(src), str(dst))
    build()


def restore_spec(kind: str, item_id: str) -> None:
    src = archive_spec_path(kind, item_id)
    dst = active_spec_path(kind, item_id)
    if not src.exists():
        raise TdgenError(f"Archived spec not found: {src}")
    if dst.exists():
        raise TdgenError(f"Active spec already exists: {dst}")
    dst.parent.mkdir(parents=True, exist_ok=True)
    shutil.move(str(src), str(dst))
    build()


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Generate BlackWoolTD datapack files from JSON specs.")
    sub = parser.add_subparsers(dest="command", required=True)
    sub.add_parser("build")
    sub.add_parser("validate")
    list_parser = sub.add_parser("list")
    list_parser.add_argument("kind", choices=["all", "enemy", "tower", "wave"])

    add_parser = sub.add_parser("add")
    add_parser.add_argument("kind", choices=["enemy", "tower", "wave"])
    add_parser.add_argument("id")
    add_parser.add_argument("--from", dest="source", required=True)

    delete_parser = sub.add_parser("delete")
    delete_parser.add_argument("kind", choices=["enemy", "tower", "wave"])
    delete_parser.add_argument("id")

    restore_parser = sub.add_parser("restore")
    restore_parser.add_argument("kind", choices=["enemy", "tower", "wave"])
    restore_parser.add_argument("id")

    args = parser.parse_args(argv)
    try:
        if args.command == "build":
            build()
        elif args.command == "validate":
            validate_specs()
        elif args.command == "list":
            list_specs(args.kind)
        elif args.command == "add":
            add_spec(args.kind, args.id, args.source)
        elif args.command == "delete":
            delete_spec(args.kind, args.id)
        elif args.command == "restore":
            restore_spec(args.kind, args.id)
        return 0
    except TdgenError as exc:
        print(f"tdgen: {exc}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
